-- Test case files under tests/cases/, run in this order. Each file returns `function(H) ... end`.
return {
    "core",
    "item_tables",
    "mainmenu",
    "story",
    "codex",
    "worldunlocks",
    "containment",
    "traders",
    "portals",
    "spawn",
    "worldinfo",
    "skills",
    "companions",
    "pets",
    "transmog",
    "bases",
    "vehicles",
    "doors",
    "players",
    "player_gaps",
    "world_gaps",
    "parity",
}
