// <auto-generated>
//   Snapshot of DT_NPC_Traders + DT_NPC_TraderItems exported by
//   AbioticEditor.Probes TraderFallbackProbe.GenerateFallback. This lets the editor
//   show traders and their per-trade unlock flags with NO game install. Item display
//   names and icons still need the game; the ids and gating flags here are exact.
//   Regenerate after a game patch; do not edit by hand.
// </auto-generated>

namespace AbioticEditor.Core.Codex;

public static partial class TraderCatalog
{
    /// <summary>
    /// Built-in trader roster used when the game's paks aren't available. Same shape as
    /// <see cref="LoadFrom"/> returns, minus pak-only portraits. Generated - see
    /// AbioticEditor.Probes TraderFallbackProbe.
    /// </summary>
    public static readonly IReadOnlyList<TraderInfo> Fallback = new TraderInfo[]
    {
        new("Marion", null, new[] { "MF_ManufacturingOpen" },
            new TraderOffer[] { new("gravitycube", 1, "Labs_Containment_Entered"), new("hose_reinforced", 1, "TrainCompletedOnce"), new("key_porcelain", 1, "Fog_Completed"), new("powercell", 1, "Fog_Completed"), new("scrap_composer", 1, "Fog_Completed"), new("organ_partial", 1, "Fog_Completed"), new("pens", 1, "Fog_Completed"), new("carapace_plutonic", 1, "Plant_ExitOpened"), new("shotgun_doublebarrel", 1, "Security_ExitOpened") },
            new TraderOffer[] { new("trinket_order", 1, null), new("tinygears", 1, null), new("gib_symph_skull", 1, null), new("key_ornate", 1, null), new("bandage", 10, null), new("anomaly", 3, null), new("syringe", 1, null), new("scrap_arcane", 5, null), new("lodestone", 1, null) }),
        new("Warren", null, System.Array.Empty<string>(),
            new TraderOffer[] { new("key_security", 1, "NightRealm_Entered"), new("magalloy", 1, "Security_Gate2Opened"), new("gunrepairkit_t1", 1, "MF_MetBlacksmith"), new("food_cannedpeas", 1, "Office_TalkedToWarren"), new("trinket_friendfinder", 1, "Office_TalkedToWarren"), new("stapler", 1, "Office_ThirdFloorReached") },
            new TraderOffer[] { new("seed_nyxshade", 1, null), new("essence_reaper", 1, null), new("brick_cpu", 1, null), new("soda_c", 1, null), new("gib_peccary_skull", 1, null), new("filet_antefish_raw", 1, null) }),
        new("Blacksmith", null, System.Array.Empty<string>(),
            new TraderOffer[] { new("lens", 1, "Manufacturing_Arrived"), new("diode", 1, "MF_MetFrake"), new("cable_fibre", 1, "MF_MetFrake"), new("suit_fire", 1, "Manufacturing_Arrived"), new("cementbag", 1, "Manufacturing_Arrived"), new("anvil", 1, "Manufacturing_Arrived"), new("steelcable", 1, "Manufacturing_Arrived"), new("acid", 1, "Manufacturing_Arrived"), new("rebar", 1, "Manufacturing_Arrived"), new("armor_helmet_weldingmask", 1, "Manufacturing_Arrived"), new("armor_arms_blacksmithinggloves", 1, "Manufacturing_Arrived") },
            new TraderOffer[] { new("hose_reinforced", 1, null), new("grease", 1, null), new("solder", 1, null), new("aircompressor", 1, null), new("scrap_metal", 1, null), new("cpu", 1, null), new("scrap_military", 1, null), new("alienwheat", 1, null), new("anomaly", 1, null), new("armor_helmet_military", 1, null), new("armor_helmet_beret", 1, null) }),
        new("Larva", null, System.Array.Empty<string>(),
            new TraderOffer[] { new("fig_larvabigorange", 1, null), new("bait_crab_gem", 1, null) },
            new TraderOffer[] { new("fish_crab_gem", 5, null), new("powderedcrystal", 1, null) }),
        new("Fili", null, System.Array.Empty<string>(),
            System.Array.Empty<TraderOffer>(),
            System.Array.Empty<TraderOffer>()),
        new("Chef", null, new[] { "Security_Entered" },
            new TraderOffer[] { new("cookbook", 1, null), new("fryingpan", 1, null), new("cookingpot", 1, null), new("seed_lettuce", 1, null), new("seed_rice", 1, null), new("food_porkchop", 1, null), new("food_potato", 1, null), new("food_seaweed", 3, "MapReveal_Dams"), new("food_latte_vanilla", 1, null), new("food_latte_pumpkin", 1, "Salem_Complete"), new("food_cider_apple", 1, "Salem_Complete"), new("food_tea_shadowberry", 1, "MapReveal_Shadowgate"), new("soda_energy", 1, null) },
            new TraderOffer[] { new("heater", 1, null), new("pens", 8, null), new("rubberbands", 8, null), new("GlowStick", 1, null), new("glowtulip", 1, null), new("gib_exorheart", 1, null), new("food_cookie", 1, null), new("cog", 1, null), new("slushie", 1, null), new("pumpkin", 1, null), new("food_apple", 2, null), new("food_shadowberry", 3, null), new("essence_leyak", 2, null) }),
        new("Grayson", null, new[] { "Grayson_Wandering", "Manufacturing_Arrived" },
            new TraderOffer[] { new("armor_helmet_hardhat", 1, "Manufacturing_Arrived"), new("armor_chest_highvisvest", 1, "Manufacturing_Arrived"), new("ammo_9mm", 4, "Manufacturing_Arrived"), new("ammo_12g", 2, "Labs_Containment_Entered"), new("ammo_Magnum", 3, "Manufacturing_Arrived"), new("ammo_308", 2, "Dams_ReachedCentral"), new("ammo_556", 1, "Dams_ReachedCentral"), new("gunrepairkit_t2", 1, "Dams_ReachedCentral") },
            new TraderOffer[] { new("salt", 1, null), new("food_tomato_super", 1, null), new("oil_robot", 1, null), new("woodplank", 1, null), new("chains", 1, null), new("growth", 1, null), new("magalloy", 1, null), new("cpu_gold", 1, null) }),
        new("Jimmy", null, System.Array.Empty<string>(),
            new TraderOffer[] { new("food_taco", 1, null), new("M_FastFood", 1, null), new("F_FastFood", 1, null) },
            new TraderOffer[] { new("anomaly", 10, null), new("food_milkshake_sberry", 1, null), new("soda_bad", 1, null) }),
        new("Thule", null, new[] { "EndBossDefeated" },
            new TraderOffer[] { new("carbonplating", 2, null), new("liquidcrystal", 2, null), new("seed_antelight_pink", 1, null) },
            new TraderOffer[] { new("coffee", 1, null), new("coffee", 1, null), new("coffee", 2, null) }),
    };
}
