-- The live-editing areas main.lua loads, in order. One module name per line (dotted, relative
-- to this Scripts folder). Add a line here when you add a file to this folder - see README.md.
return {
    "areas.story",
    "areas.bases",
    "areas.care",
    "areas.playtime",
    "areas.vehicles",
    "areas.pets",
    "areas.containment",
    "areas.traders",
    "areas.portals",
    "areas.elevators",
    "areas.spawn",
    "areas.companions",
    "areas.recipes",
    "areas.codex",
    "areas.general",
    "areas.appearance",
    "areas.worldunlocks",
    "areas.transmog",
    "areas.narrative",
    "areas.buttons",
    "areas.resourcenodes",
    "areas.destructibles",
    "areas.corpses",
    "areas.powersockets",
    "areas.trams",
    "areas.npcspawns",
    "areas.triggers",
}
