blank_issues_enabled: true
contact_links:
  - name: Nexus Mods posts
    url: https://www.nexusmods.com/abioticfactor/mods/244?tab=posts
    about: Have an idea, a question, or would rather not use GitHub? Post on the Nexus Mods page instead.
