using System.IO;
using System.Text;
using AbioticEditor.Core.Assets;
using AbioticEditor.Core.Codex;
using Xunit.Abstractions;

namespace AbioticEditor.Tests;

/// <summary>
/// Generator: exports the live trader roster (<c>DT_NPC_Traders</c> + <c>DT_NPC_TraderItems</c>)
/// from the installed game as the C# source for <see cref="TraderCatalog.Fallback"/>, so the
/// editor can show traders and their per-trade unlock flags WITHOUT the game installed. Writes to
/// <c>%TEMP%/abiotic-editor-schema/TraderCatalogFallback.cs</c>; paste the result into
/// <c>src/AbioticEditor.Core/Codex/TraderCatalogFallback.cs</c> after a game patch.
/// Mirrors <see cref="AbioticEditor.Tests.AllFlagsProbe"/>'s dump-then-paste workflow.
/// </summary>
public class TraderFallbackProbe
{
    private readonly ITestOutputHelper _output;

    public TraderFallbackProbe(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void GenerateFallback()
    {
        using var provider = GameAssetProvider.CreateForLocalInstall();
        if (provider is null || !provider.HasMappings)
        {
            _output.WriteLine("No game data available (paks/mappings) - cannot generate the snapshot.");
            return;
        }

        var traders = TraderCatalog.LoadFrom(provider);
        _output.WriteLine($"Loaded {traders.Count} traders.");
        Assert.True(traders.Count > 0, "expected at least one trader from the game tables");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Snapshot of DT_NPC_Traders + DT_NPC_TraderItems exported by");
        sb.AppendLine("//   AbioticEditor.Probes TraderFallbackProbe.GenerateFallback. This lets the editor");
        sb.AppendLine("//   show traders and their per-trade unlock flags with NO game install. Item display");
        sb.AppendLine("//   names and icons still need the game; the ids and gating flags here are exact.");
        sb.AppendLine("//   Regenerate after a game patch; do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace AbioticEditor.Core.Codex;");
        sb.AppendLine();
        sb.AppendLine("public static partial class TraderCatalog");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Built-in trader roster used when the game's paks aren't available. Same shape as");
        sb.AppendLine("    /// <see cref=\"LoadFrom\"/> returns, minus pak-only portraits. Generated - see");
        sb.AppendLine("    /// AbioticEditor.Probes TraderFallbackProbe.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static readonly IReadOnlyList<TraderInfo> Fallback = new TraderInfo[]");
        sb.AppendLine("    {");
        foreach (var t in traders)
        {
            sb.AppendLine($"        new({Str(t.Id)}, null, {Flags(t.RequiredFlags)},");
            sb.AppendLine($"            {Offers(t.Sells)},");
            sb.AppendLine($"            {Offers(t.Accepts)}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        var outDir = Path.Combine(Path.GetTempPath(), "abiotic-editor-schema");
        Directory.CreateDirectory(outDir);
        var outPath = Path.Combine(outDir, "TraderCatalogFallback.cs");
        File.WriteAllText(outPath, sb.ToString());
        _output.WriteLine($"Wrote {outPath}");
        _output.WriteLine("");
        _output.WriteLine(sb.ToString());
    }

    private static string Str(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Flags(IReadOnlyList<string> flags)
        => flags.Count == 0
            ? "System.Array.Empty<string>()"
            : "new[] { " + string.Join(", ", flags.Select(Str)) + " }";

    private static string Offers(IReadOnlyList<TraderOffer> offers)
    {
        if (offers.Count == 0) return "System.Array.Empty<TraderOffer>()";
        var parts = offers.Select(o =>
            $"new({Str(o.ItemId)}, {o.Count}, {(o.RequiredFlag is null ? "null" : Str(o.RequiredFlag))})");
        return "new TraderOffer[] { " + string.Join(", ", parts) + " }";
    }
}
