// Renders where each level door, button, breakable wall, elevator, tram and teleporter is: the level
// around it from above at an angle, ceiling cut away, the thing outlined and pinned. Level actors
// stand in the same place in every world, so these ship with the editor like the kind pictures.
// Output: src/AbioticEditor.Web.Shared/wwwroot/thumbs/places/<map>/<actor>.webp and the generated
// WorldThumbnails.Places.g.cs. Pictures already rendered are kept (delete one to render it again).
//
// Usage (see README.md):
//   node places.mjs <editor url> <instances.json> [limit]
import { chromium } from "playwright";
import { readFile, writeFile, mkdir, access, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const [url = "http://127.0.0.1:37361", instancesFile, limitArg] = process.argv.slice(2);
if (!instancesFile) {
    console.error("usage: node places.mjs <editor url> <instances.json> [limit]");
    process.exit(2);
}
const kinds = new Set(["doors", "buttons", "destructibles", "elevators", "trams", "portals", "resource-nodes", "power-sockets", "corpses"]);
const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const outRoot = join(repo, "src", "AbioticEditor.Web.Shared", "wwwroot", "thumbs", "places");

/** "/Game/Maps/Facility_Office1.Facility_Office1:PersistentLevel.BlastDoor_C_2" -> ["Facility_Office1", "BlastDoor_C_2"]. */
function mapAndActor(path) {
    const colon = path.indexOf(":");
    const pkg = path.slice(0, colon < 0 ? path.length : colon);
    const map = pkg.slice(pkg.lastIndexOf(".") + 1);
    const actor = path.slice(Math.max(path.lastIndexOf("."), colon) + 1);
    return [map, actor];
}

const all = JSON.parse(await readFile(instancesFile, "utf8")).filter(t => kinds.has(t.kind));
const seen = new Set();
const todo = [];
for (const t of all) {
    const [map, actor] = mapAndActor(t.actor);
    const key = `${map}:${actor}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const file = join(outRoot, map, `${actor}.webp`);
    try { await access(file); continue; } catch { /* not rendered yet */ }
    todo.push({ ...t, map, name: actor, file });
}
const limit = Number(limitArg ?? todo.length);

const browser = await chromium.launch({ args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 800, height: 800 } });
await page.goto(`${url}/healthz`);
await page.evaluate(async () => {
    const host = document.createElement("div");
    host.style.cssText = "width:400px;height:400px;position:fixed;left:0;top:0";
    document.body.appendChild(host);
    const module = await import("/_content/AbioticEditor.Web.Shared/base3d.js");
    window.__shotView = module.createView(host, { invokeMethodAsync: async () => { } });
});

let written = 0;
const started = Date.now();
for (const t of todo.slice(0, limit)) {
    const result = await page.evaluate(async t => {
        let center = t.center, front = t.front;
        if (!center) {
            const at = await fetch(`/scene-models/actor?path=${encodeURIComponent(t.actor)}`);
            if (!at.ok) return { error: `no position (${at.status})` };
            ({ p: center, front } = await at.json());
        }
        try { return await window.__shotView.locationShot({ region: t.region, actor: t.actor, center, front }); }
        catch (e) { return { error: String(e) }; }
    }, t);
    if (!result || result.error || !result.image) {
        console.log(`skip ${t.map}:${t.name}: ${result?.error ?? "nothing drawn"}`);
        continue;
    }
    await mkdir(dirname(t.file), { recursive: true });
    await writeFile(t.file, Buffer.from(result.image.split(",")[1], "base64"));
    written++;
    if (written % 25 === 0) console.log(`${written} written (${Math.round((Date.now() - started) / written)} ms each)`);
}
await browser.close();

// The index lists every picture on disk (not only this run's), so runs can be resumed.
const keys = [];
try {
    for (const map of await readdir(outRoot)) {
        for (const file of await readdir(join(outRoot, map))) {
            if (file.endsWith(".webp")) keys.push(`${map}:${file.slice(0, -5)}`);
        }
    }
} catch { /* no pictures yet */ }
keys.sort();
const index = `// <auto-generated>Written by tools/thumbnails/places.mjs; re-run it to update.</auto-generated>
namespace AbioticEditor.Web.Services;

public static partial class WorldThumbnails
{
    private static readonly HashSet<string> Places = new(StringComparer.OrdinalIgnoreCase)
    {
${keys.map(k => `        "${k}",`).join("\n")}
    };
}
`;
await writeFile(join(repo, "src", "AbioticEditor.Web.Shared", "Services", "WorldThumbnails.Places.g.cs"), index);
console.log(`${written} new pictures, ${keys.length} in total, ${todo.length - Math.min(limit, todo.length)} left`);
