// Renders the pictures the editor's 2D lists show for doors, buttons, breakable walls, elevators,
// trams, teleporters and resource nodes: each kind drawn on its own with the game's own models,
// from a running editor (which reads them from the installed game), into
// src/AbioticEditor.Web.Shared/wwwroot/thumbs/<kind>/<class>.webp plus a generated C# index.
//
// Usage (see README.md):
//   node render.mjs <editor url> <targets.json> [size]
import { chromium } from "playwright";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const [url = "http://127.0.0.1:37361", targetsFile, sizeArg] = process.argv.slice(2);
if (!targetsFile) {
    console.error("usage: node render.mjs <editor url> <targets.json> [size]");
    process.exit(2);
}
const size = Number(sizeArg ?? 256);
const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const outRoot = join(repo, "src", "AbioticEditor.Web.Shared", "wwwroot", "thumbs");
const targets = JSON.parse(await readFile(targetsFile, "utf8"));

const browser = await chromium.launch({ args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader"] });
const page = await browser.newPage({ viewport: { width: 800, height: 800 } });
await page.goto(`${url}/healthz`);
await page.evaluate(async () => {
    const host = document.createElement("div");
    host.style.cssText = "width:400px;height:400px;position:fixed;left:0;top:0";
    document.body.appendChild(host);
    const module = await import("/_content/AbioticEditor.Web.Shared/base3d.js");
    window.__thumbView = module.createView(host, { invokeMethodAsync: async () => { } });
});

const done = [];
for (const t of targets) {
    const result = await page.evaluate(async t => {
        const at = await fetch(`/scene-models/actor?path=${encodeURIComponent(t.actor)}`);
        if (!at.ok) return { error: `no position (${at.status})` };
        const center = await at.json();
        try {
            return await window.__thumbView.thumbnail({ region: t.region, actor: t.actor, center, size: t.size });
        } catch (e) {
            return { error: String(e) };
        }
    }, { ...t, size });
    if (!result || result.error || !result.image) {
        console.log(`skip ${t.kind}/${t.cls}: ${result?.error ?? "no pieces"}`);
        continue;
    }
    const file = join(outRoot, t.kind, `${t.cls}.webp`);
    await mkdir(dirname(file), { recursive: true });
    await writeFile(file, Buffer.from(result.image.split(",")[1], "base64"));
    done.push(t);
    console.log(`ok   ${t.kind}/${t.cls} (${result.pieces} pieces)`);
}
await browser.close();

// The editor needs to know which pictures exist without asking the server (the browser build has
// no file listing), so the list is written as code next to the pictures.
const byKind = {};
for (const t of done) (byKind[t.kind] ??= []).push(t.cls);
const lines = Object.entries(byKind).sort(([a], [b]) => a.localeCompare(b)).map(([kind, classes]) =>
    `        ["${kind}"] = new(StringComparer.Ordinal) { ${classes.sort().map(c => `"${c}"`).join(", ")} },`);
const index = `// <auto-generated>Written by tools/thumbnails/render.mjs; re-run it to update.</auto-generated>
namespace AbioticEditor.Web.Services;

public static partial class WorldThumbnails
{
    private static readonly Dictionary<string, HashSet<string>> Available = new(StringComparer.Ordinal)
    {
${lines.join("\n")}
    };
}
`;
await writeFile(join(repo, "src", "AbioticEditor.Web.Shared", "Services", "WorldThumbnails.Index.g.cs"), index);
console.log(`${done.length} of ${targets.length} pictures written to ${outRoot}`);
